// <auto-generated />
using System;
using FirstEFCoreApplication;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FirstEFCoreApplication.Migrations
{
    [DbContext(typeof(CareContext))]
    [Migration("20210427121310_CreateTableVisitors")]
    partial class CreateTableVisitors
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FirstEFCoreApplication.Models.CareTaker", b =>
                {
                    b.Property<int>("CareTakerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prename")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CareTakerId");

                    b.ToTable("CareTakers");
                });

            modelBuilder.Entity("FirstEFCoreApplication.Models.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CareLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prename")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResidentId");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("FirstEFCoreApplication.Models.ResidentCareTaker", b =>
                {
                    b.Property<int>("CareTakerId")
                        .HasColumnType("int");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.HasKey("CareTakerId", "ResidentId");

                    b.HasIndex("ResidentId");

                    b.ToTable("ResidentCareTaker");
                });

            modelBuilder.Entity("FirstEFCoreApplication.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Equipment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.HasIndex("ResidentId")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("FirstEFCoreApplication.Models.Visitor", b =>
                {
                    b.Property<int>("VisitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int");

                    b.HasKey("VisitorId");

                    b.HasIndex("ResidentId");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("FirstEFCoreApplication.Models.ResidentCareTaker", b =>
                {
                    b.HasOne("FirstEFCoreApplication.Models.CareTaker", "CareTaker")
                        .WithMany("ResidentCareTakers")
                        .HasForeignKey("CareTakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirstEFCoreApplication.Models.Resident", "Resident")
                        .WithMany("ResidentCareTakers")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareTaker");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("FirstEFCoreApplication.Models.Room", b =>
                {
                    b.HasOne("FirstEFCoreApplication.Models.Resident", "Resident")
                        .WithOne("Room")
                        .HasForeignKey("FirstEFCoreApplication.Models.Room", "ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("FirstEFCoreApplication.Models.Visitor", b =>
                {
                    b.HasOne("FirstEFCoreApplication.Models.Resident", null)
                        .WithMany("Visitors")
                        .HasForeignKey("ResidentId");
                });

            modelBuilder.Entity("FirstEFCoreApplication.Models.CareTaker", b =>
                {
                    b.Navigation("ResidentCareTakers");
                });

            modelBuilder.Entity("FirstEFCoreApplication.Models.Resident", b =>
                {
                    b.Navigation("ResidentCareTakers");

                    b.Navigation("Room");

                    b.Navigation("Visitors");
                });
#pragma warning restore 612, 618
        }
    }
}
